import React from "react";
import DownloadIcon from "@mui/icons-material/Download";
import UploadIcon from "@mui/icons-material/Upload";
import QrCode from "qrcode";
import {Alert, Box, Button, FormControl, Grid, InputLabel, MenuItem, Select, Slider, Stack, TextField, Typography} from "@mui/material";
import type {SelectChangeEvent} from "@mui/material/Select";
import {useLocalStorageState} from "../shared/hooks";
import {ToolHeader, ToolSurface} from "../shared/ToolScaffold";

type QrFormat = "image/png" | "image/jpeg" | "image/webp" | "svg";
type ErrorCorrectionLevel = "L" | "M" | "Q" | "H";
type QrPreset = "free" | "url" | "wifi" | "email" | "sms" | "vcard";

const svgToDataUrl = (svg: string) => `data:image/svg+xml;base64,${btoa(unescape(encodeURIComponent(svg)))}`;

const fileToDataUrl = (file: File) => new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = () => reject(reader.error ?? new Error("Failed to read file"));
    reader.readAsDataURL(file);
});

const loadImage = (src: string) => new Promise<HTMLImageElement>((resolve, reject) => {
    const image = new Image();
    image.onload = () => resolve(image);
    image.onerror = () => reject(new Error("Failed to load image"));
    image.src = src;
});

const embedLogoInRaster = async (baseDataUrl: string, logoDataUrl: string, sizeRatio: number, mimeType: string, quality: number) => {
    const [qrImage, logoImage] = await Promise.all([loadImage(baseDataUrl), loadImage(logoDataUrl)]);
    const canvas = document.createElement("canvas");
    canvas.width = qrImage.naturalWidth;
    canvas.height = qrImage.naturalHeight;
    const context = canvas.getContext("2d");
    if (!context) throw new Error("Canvas unavailable");
    context.drawImage(qrImage, 0, 0);
    const logoSize = Math.round(canvas.width * sizeRatio);
    const x = (canvas.width - logoSize) / 2;
    const y = (canvas.height - logoSize) / 2;
    const pad = Math.round(logoSize * 0.12);
    context.fillStyle = "#ffffff";
    context.fillRect(x - pad, y - pad, logoSize + pad * 2, logoSize + pad * 2);
    context.drawImage(logoImage, x, y, logoSize, logoSize);
    return canvas.toDataURL(mimeType, quality);
};

const embedLogoInSvg = (svg: string, logoDataUrl: string, sizeRatio: number) => {
    const doc = new DOMParser().parseFromString(svg, "image/svg+xml");
    const svgEl = doc.documentElement;
    const width = Number(svgEl.getAttribute("width")) || 100;
    const height = Number(svgEl.getAttribute("height")) || 100;
    const logoSize = width * sizeRatio;
    const x = (width - logoSize) / 2;
    const y = (height - logoSize) / 2;
    const pad = logoSize * 0.12;
    const ns = "http://www.w3.org/2000/svg";
    const rect = doc.createElementNS(ns, "rect");
    rect.setAttribute("x", String(x - pad));
    rect.setAttribute("y", String(y - pad));
    rect.setAttribute("width", String(logoSize + pad * 2));
    rect.setAttribute("height", String(logoSize + pad * 2));
    rect.setAttribute("fill", "#ffffff");
    const image = doc.createElementNS(ns, "image");
    image.setAttribute("x", String(x));
    image.setAttribute("y", String(y));
    image.setAttribute("width", String(logoSize));
    image.setAttribute("height", String(logoSize));
    image.setAttribute("href", logoDataUrl);
    svgEl.appendChild(rect);
    svgEl.appendChild(image);
    return new XMLSerializer().serializeToString(svgEl);
};

const QrTool = () => {
    const [text, setText] = useLocalStorageState("qr.text", "https://github.com/");
    const [format, setFormat] = useLocalStorageState<QrFormat>("qr.format", "image/png");
    const [errorCorrectionLevel, setErrorCorrectionLevel] = useLocalStorageState<ErrorCorrectionLevel>("qr.ec", "M");
    const [dark, setDark] = useLocalStorageState("qr.dark", "#000000");
    const [light, setLight] = useLocalStorageState("qr.light", "#ffffff");
    const [margin, setMargin] = useLocalStorageState("qr.margin", 2);
    const [scale, setScale] = useLocalStorageState("qr.scale", 6);
    const [quality, setQuality] = useLocalStorageState("qr.quality", 0.9);
    const [preset, setPreset] = useLocalStorageState<QrPreset>("qr.preset", "free");
    const [presetFields, setPresetFields] = useLocalStorageState("qr.presetFields", {
        url: "https://github.com/",
        ssid: "My Wi-Fi",
        password: "",
        encryption: "WPA",
        email: "hello@example.com",
        subject: "Hello",
        body: "Generated by ToolBench",
        phone: "+15555550123",
        firstName: "Ada",
        lastName: "Lovelace",
        organization: "Analytical Engines",
        website: "https://example.com"
    });
    const [logoDataUrl, setLogoDataUrl] = React.useState<string | null>(null);
    const [logoSizeRatio, setLogoSizeRatio] = useLocalStorageState("qr.logoSizeRatio", 0.22);
    const [logoError, setLogoError] = React.useState("");
    const [dataUrl, setDataUrl] = React.useState("");
    const extension = format === "svg" ? "svg" : format.split("/")[1];

    const handleLogoFile = async (file: File | undefined) => {
        if (!file) return;
        try {
            setLogoDataUrl(await fileToDataUrl(file));
            setLogoError("");
        } catch {
            setLogoError("Failed to read logo image");
        }
    };

    const updatePresetField = (key: keyof typeof presetFields, value: string) => {
        setPresetFields({...presetFields, [key]: value});
    };

    const applyPreset = () => {
        if (preset === "url") setText(presetFields.url);
        if (preset === "wifi") setText(`WIFI:T:${presetFields.encryption};S:${presetFields.ssid};P:${presetFields.password};;`);
        if (preset === "email") setText(`mailto:${presetFields.email}?subject=${encodeURIComponent(presetFields.subject)}&body=${encodeURIComponent(presetFields.body)}`);
        if (preset === "sms") setText(`SMSTO:${presetFields.phone}:${presetFields.body}`);
        if (preset === "vcard") {
            setText([
                "BEGIN:VCARD",
                "VERSION:3.0",
                `N:${presetFields.lastName};${presetFields.firstName};;;`,
                `FN:${presetFields.firstName} ${presetFields.lastName}`,
                `ORG:${presetFields.organization}`,
                `TEL:${presetFields.phone}`,
                `EMAIL:${presetFields.email}`,
                `URL:${presetFields.website}`,
                "END:VCARD"
            ].join("\n"));
        }
    };

    React.useEffect(() => {
        let cancelled = false;
        const options = {
            errorCorrectionLevel,
            margin,
            scale,
            quality,
            color: {dark, light}
        };

        const build = async () => {
            try {
                if (format === "svg") {
                    const svg = await QrCode.toString(text || " ", {...options, type: "svg"});
                    const finalSvg = logoDataUrl ? embedLogoInSvg(svg, logoDataUrl, logoSizeRatio) : svg;
                    if (!cancelled) setDataUrl(svgToDataUrl(finalSvg));
                } else {
                    const base = await QrCode.toDataURL(text || " ", {...options, type: format});
                    const finalDataUrl = logoDataUrl ? await embedLogoInRaster(base, logoDataUrl, logoSizeRatio, format, quality) : base;
                    if (!cancelled) setDataUrl(finalDataUrl);
                }
                if (!cancelled) setLogoError("");
            } catch (err) {
                if (!cancelled) setLogoError(err instanceof Error ? err.message : "Failed to render QR code");
            }
        };

        build();
        return () => {
            cancelled = true;
        };
    }, [dark, errorCorrectionLevel, format, light, logoDataUrl, logoSizeRatio, margin, quality, scale, text]);

    return (
        <ToolSurface>
            <ToolHeader title="QR Code Creator" description="Generate downloadable QR codes with format, color, and correction controls."/>
            <Stack spacing={3}>
                <FormControl>
                    <InputLabel>Preset builder</InputLabel>
                    <Select value={preset} label="Preset builder" onChange={(event: SelectChangeEvent) => setPreset(event.target.value as QrPreset)}>
                        <MenuItem value="free">Free text</MenuItem>
                        <MenuItem value="url">URL</MenuItem>
                        <MenuItem value="wifi">Wi-Fi</MenuItem>
                        <MenuItem value="email">Email</MenuItem>
                        <MenuItem value="sms">SMS</MenuItem>
                        <MenuItem value="vcard">vCard</MenuItem>
                    </Select>
                </FormControl>
                {preset !== "free" && (
                    <Grid container spacing={2}>
                        {preset === "url" && <Grid size={{xs: 12}}><TextField label="URL" value={presetFields.url} onChange={event => updatePresetField("url", event.target.value)} fullWidth/></Grid>}
                        {preset === "wifi" && (
                            <>
                                <Grid size={{xs: 12, sm: 4}}><TextField label="SSID" value={presetFields.ssid} onChange={event => updatePresetField("ssid", event.target.value)} fullWidth/></Grid>
                                <Grid size={{xs: 12, sm: 4}}><TextField label="Password" value={presetFields.password} onChange={event => updatePresetField("password", event.target.value)} fullWidth/></Grid>
                                <Grid size={{xs: 12, sm: 4}}><TextField label="Encryption" value={presetFields.encryption} onChange={event => updatePresetField("encryption", event.target.value)} fullWidth/></Grid>
                            </>
                        )}
                        {(preset === "email" || preset === "vcard") && <Grid size={{xs: 12, sm: 6}}><TextField label="Email" value={presetFields.email} onChange={event => updatePresetField("email", event.target.value)} fullWidth/></Grid>}
                        {preset === "email" && <Grid size={{xs: 12, sm: 6}}><TextField label="Subject" value={presetFields.subject} onChange={event => updatePresetField("subject", event.target.value)} fullWidth/></Grid>}
                        {(preset === "email" || preset === "sms") && <Grid size={{xs: 12}}><TextField label="Body" value={presetFields.body} onChange={event => updatePresetField("body", event.target.value)} fullWidth/></Grid>}
                        {(preset === "sms" || preset === "vcard") && <Grid size={{xs: 12, sm: 6}}><TextField label="Phone" value={presetFields.phone} onChange={event => updatePresetField("phone", event.target.value)} fullWidth/></Grid>}
                        {preset === "vcard" && (
                            <>
                                <Grid size={{xs: 12, sm: 6}}><TextField label="First name" value={presetFields.firstName} onChange={event => updatePresetField("firstName", event.target.value)} fullWidth/></Grid>
                                <Grid size={{xs: 12, sm: 6}}><TextField label="Last name" value={presetFields.lastName} onChange={event => updatePresetField("lastName", event.target.value)} fullWidth/></Grid>
                                <Grid size={{xs: 12, sm: 6}}><TextField label="Organization" value={presetFields.organization} onChange={event => updatePresetField("organization", event.target.value)} fullWidth/></Grid>
                                <Grid size={{xs: 12, sm: 6}}><TextField label="Website" value={presetFields.website} onChange={event => updatePresetField("website", event.target.value)} fullWidth/></Grid>
                            </>
                        )}
                        <Grid size={{xs: 12}}>
                            <Button variant="contained" onClick={applyPreset}>Apply preset</Button>
                        </Grid>
                    </Grid>
                )}
                <TextField label="Text" value={text} onChange={event => setText(event.target.value)} multiline minRows={4}/>
                <Grid container spacing={2}>
                    <Grid size={{xs: 12, sm: 6}}>
                        <FormControl fullWidth>
                            <InputLabel>Format</InputLabel>
                            <Select value={format} label="Format" onChange={(event: SelectChangeEvent) => setFormat(event.target.value as QrFormat)}>
                                <MenuItem value="svg">SVG</MenuItem>
                                <MenuItem value="image/png">PNG</MenuItem>
                                <MenuItem value="image/jpeg">JPG</MenuItem>
                                <MenuItem value="image/webp">WEBP</MenuItem>
                            </Select>
                        </FormControl>
                    </Grid>
                    <Grid size={{xs: 12, sm: 6}}>
                        <FormControl fullWidth>
                            <InputLabel>Error correction</InputLabel>
                            <Select value={errorCorrectionLevel} label="Error correction" onChange={(event: SelectChangeEvent) => setErrorCorrectionLevel(event.target.value as ErrorCorrectionLevel)}>
                                <MenuItem value="L">L (~7%)</MenuItem>
                                <MenuItem value="M">M (~15%)</MenuItem>
                                <MenuItem value="Q">Q (~25%)</MenuItem>
                                <MenuItem value="H">H (~30%)</MenuItem>
                            </Select>
                        </FormControl>
                    </Grid>
                    <Grid size={{xs: 12, sm: 6}}>
                        <TextField label="Foreground" type="color" value={dark} onChange={event => setDark(event.target.value)} fullWidth/>
                    </Grid>
                    <Grid size={{xs: 12, sm: 6}}>
                        <TextField label="Background" type="color" value={light} onChange={event => setLight(event.target.value)} fullWidth/>
                    </Grid>
                </Grid>
                <Stack spacing={1.5}>
                    <Typography variant="subtitle2">Logo</Typography>
                    <Stack direction={{xs: "column", sm: "row"}} spacing={1} sx={{alignItems: {sm: "center"}}}>
                        <Button component="label" variant="outlined" startIcon={<UploadIcon/>}>
                            {logoDataUrl ? "Replace logo" : "Upload logo"}
                            <input hidden type="file" accept="image/*" onChange={event => handleLogoFile(event.target.files?.[0])}/>
                        </Button>
                        {logoDataUrl && (
                            <>
                                <Box component="img" src={logoDataUrl} alt="Logo preview" sx={{width: 40, height: 40, objectFit: "contain", borderRadius: 1, border: 1, borderColor: "divider"}}/>
                                <Button color="inherit" onClick={() => setLogoDataUrl(null)}>Remove logo</Button>
                            </>
                        )}
                    </Stack>
                    {logoDataUrl && (
                        <Box>
                            <Typography gutterBottom>Logo size: {Math.round(logoSizeRatio * 100)}%</Typography>
                            <Slider value={logoSizeRatio} min={0.1} max={0.35} step={0.01} onChange={(_, value) => setLogoSizeRatio(value as number)}/>
                        </Box>
                    )}
                    {logoDataUrl && errorCorrectionLevel !== "H" && (
                        <Alert severity="info">Use error correction level H for the most reliable scans with a logo.</Alert>
                    )}
                    {logoError && <Alert severity="error">{logoError}</Alert>}
                </Stack>
                <Box>
                    <Typography gutterBottom>Margin: {margin}</Typography>
                    <Slider value={margin} min={0} max={10} step={1} onChange={(_, value) => setMargin(value as number)}/>
                </Box>
                <Box>
                    <Typography gutterBottom>Scale: {scale}</Typography>
                    <Slider value={scale} min={2} max={16} step={1} onChange={(_, value) => setScale(value as number)}/>
                </Box>
                {(format === "image/jpeg" || format === "image/webp") && (
                    <Box>
                        <Typography gutterBottom>Quality: {quality}</Typography>
                        <Slider value={quality} min={0.1} max={1} step={0.05} onChange={(_, value) => setQuality(value as number)}/>
                    </Box>
                )}
                {dataUrl && (
                    <Box sx={{textAlign: "center"}}>
                        <Box component="img" src={dataUrl} alt="QR code" sx={{width: "100%", maxWidth: 360, borderRadius: 2}}/>
                    </Box>
                )}
                <Button
                    startIcon={<DownloadIcon/>}
                    href={dataUrl || undefined}
                    download={`qr-code.${extension}`}
                    disabled={!dataUrl}
                >
                    Download {extension.toUpperCase()}
                </Button>
            </Stack>
        </ToolSurface>
    );
};

export default QrTool;
