import React from "react";
import DownloadIcon from "@mui/icons-material/Download";
import QrCode from "qrcode";
import {Box, Button, FormControl, Grid, InputLabel, MenuItem, Select, Slider, Stack, TextField, Typography} from "@mui/material";
import type {SelectChangeEvent} from "@mui/material/Select";
import {useLocalStorageState} from "../shared/hooks";
import {ToolHeader, ToolSurface} from "../shared/ToolScaffold";

type QrFormat = "image/png" | "image/jpeg" | "image/webp" | "svg";
type ErrorCorrectionLevel = "L" | "M" | "Q" | "H";
type QrPreset = "free" | "url" | "wifi" | "email" | "sms" | "vcard";

const svgToDataUrl = (svg: string) => `data:image/svg+xml;base64,${btoa(unescape(encodeURIComponent(svg)))}`;

const QrTool = () => {
    const [text, setText] = useLocalStorageState("qr.text", "https://github.com/");
    const [format, setFormat] = useLocalStorageState<QrFormat>("qr.format", "image/png");
    const [errorCorrectionLevel, setErrorCorrectionLevel] = useLocalStorageState<ErrorCorrectionLevel>("qr.ec", "M");
    const [dark, setDark] = useLocalStorageState("qr.dark", "#000000");
    const [light, setLight] = useLocalStorageState("qr.light", "#ffffff");
    const [margin, setMargin] = useLocalStorageState("qr.margin", 2);
    const [scale, setScale] = useLocalStorageState("qr.scale", 6);
    const [quality, setQuality] = useLocalStorageState("qr.quality", 0.9);
    const [preset, setPreset] = useLocalStorageState<QrPreset>("qr.preset", "free");
    const [presetFields, setPresetFields] = useLocalStorageState("qr.presetFields", {
        url: "https://github.com/",
        ssid: "My Wi-Fi",
        password: "",
        encryption: "WPA",
        email: "hello@example.com",
        subject: "Hello",
        body: "Generated by ToolBench",
        phone: "+15555550123",
        firstName: "Ada",
        lastName: "Lovelace",
        organization: "Analytical Engines",
        website: "https://example.com"
    });
    const [dataUrl, setDataUrl] = React.useState("");
    const extension = format === "svg" ? "svg" : format.split("/")[1];

    const updatePresetField = (key: keyof typeof presetFields, value: string) => {
        setPresetFields({...presetFields, [key]: value});
    };

    const applyPreset = () => {
        if (preset === "url") setText(presetFields.url);
        if (preset === "wifi") setText(`WIFI:T:${presetFields.encryption};S:${presetFields.ssid};P:${presetFields.password};;`);
        if (preset === "email") setText(`mailto:${presetFields.email}?subject=${encodeURIComponent(presetFields.subject)}&body=${encodeURIComponent(presetFields.body)}`);
        if (preset === "sms") setText(`SMSTO:${presetFields.phone}:${presetFields.body}`);
        if (preset === "vcard") {
            setText([
                "BEGIN:VCARD",
                "VERSION:3.0",
                `N:${presetFields.lastName};${presetFields.firstName};;;`,
                `FN:${presetFields.firstName} ${presetFields.lastName}`,
                `ORG:${presetFields.organization}`,
                `TEL:${presetFields.phone}`,
                `EMAIL:${presetFields.email}`,
                `URL:${presetFields.website}`,
                "END:VCARD"
            ].join("\n"));
        }
    };

    React.useEffect(() => {
        const options = {
            errorCorrectionLevel,
            margin,
            scale,
            quality,
            color: {dark, light}
        };
        if (format === "svg") {
            QrCode.toString(text || " ", {...options, type: "svg"}).then(svg => setDataUrl(svgToDataUrl(svg)));
        } else {
            QrCode.toDataURL(text || " ", {...options, type: format}).then(setDataUrl);
        }
    }, [dark, errorCorrectionLevel, format, light, margin, quality, scale, text]);

    return (
        <ToolSurface>
            <ToolHeader title="QR Code Creator" description="Generate downloadable QR codes with format, color, and correction controls."/>
            <Stack spacing={3}>
                <FormControl>
                    <InputLabel>Preset builder</InputLabel>
                    <Select value={preset} label="Preset builder" onChange={(event: SelectChangeEvent) => setPreset(event.target.value as QrPreset)}>
                        <MenuItem value="free">Free text</MenuItem>
                        <MenuItem value="url">URL</MenuItem>
                        <MenuItem value="wifi">Wi-Fi</MenuItem>
                        <MenuItem value="email">Email</MenuItem>
                        <MenuItem value="sms">SMS</MenuItem>
                        <MenuItem value="vcard">vCard</MenuItem>
                    </Select>
                </FormControl>
                {preset !== "free" && (
                    <Grid container spacing={2}>
                        {preset === "url" && <Grid size={{xs: 12}}><TextField label="URL" value={presetFields.url} onChange={event => updatePresetField("url", event.target.value)} fullWidth/></Grid>}
                        {preset === "wifi" && (
                            <>
                                <Grid size={{xs: 12, sm: 4}}><TextField label="SSID" value={presetFields.ssid} onChange={event => updatePresetField("ssid", event.target.value)} fullWidth/></Grid>
                                <Grid size={{xs: 12, sm: 4}}><TextField label="Password" value={presetFields.password} onChange={event => updatePresetField("password", event.target.value)} fullWidth/></Grid>
                                <Grid size={{xs: 12, sm: 4}}><TextField label="Encryption" value={presetFields.encryption} onChange={event => updatePresetField("encryption", event.target.value)} fullWidth/></Grid>
                            </>
                        )}
                        {(preset === "email" || preset === "vcard") && <Grid size={{xs: 12, sm: 6}}><TextField label="Email" value={presetFields.email} onChange={event => updatePresetField("email", event.target.value)} fullWidth/></Grid>}
                        {preset === "email" && <Grid size={{xs: 12, sm: 6}}><TextField label="Subject" value={presetFields.subject} onChange={event => updatePresetField("subject", event.target.value)} fullWidth/></Grid>}
                        {(preset === "email" || preset === "sms") && <Grid size={{xs: 12}}><TextField label="Body" value={presetFields.body} onChange={event => updatePresetField("body", event.target.value)} fullWidth/></Grid>}
                        {(preset === "sms" || preset === "vcard") && <Grid size={{xs: 12, sm: 6}}><TextField label="Phone" value={presetFields.phone} onChange={event => updatePresetField("phone", event.target.value)} fullWidth/></Grid>}
                        {preset === "vcard" && (
                            <>
                                <Grid size={{xs: 12, sm: 6}}><TextField label="First name" value={presetFields.firstName} onChange={event => updatePresetField("firstName", event.target.value)} fullWidth/></Grid>
                                <Grid size={{xs: 12, sm: 6}}><TextField label="Last name" value={presetFields.lastName} onChange={event => updatePresetField("lastName", event.target.value)} fullWidth/></Grid>
                                <Grid size={{xs: 12, sm: 6}}><TextField label="Organization" value={presetFields.organization} onChange={event => updatePresetField("organization", event.target.value)} fullWidth/></Grid>
                                <Grid size={{xs: 12, sm: 6}}><TextField label="Website" value={presetFields.website} onChange={event => updatePresetField("website", event.target.value)} fullWidth/></Grid>
                            </>
                        )}
                        <Grid size={{xs: 12}}>
                            <Button variant="contained" onClick={applyPreset}>Apply preset</Button>
                        </Grid>
                    </Grid>
                )}
                <TextField label="Text" value={text} onChange={event => setText(event.target.value)} multiline minRows={4}/>
                <Grid container spacing={2}>
                    <Grid size={{xs: 12, sm: 6}}>
                        <FormControl fullWidth>
                            <InputLabel>Format</InputLabel>
                            <Select value={format} label="Format" onChange={(event: SelectChangeEvent) => setFormat(event.target.value as QrFormat)}>
                                <MenuItem value="svg">SVG</MenuItem>
                                <MenuItem value="image/png">PNG</MenuItem>
                                <MenuItem value="image/jpeg">JPG</MenuItem>
                                <MenuItem value="image/webp">WEBP</MenuItem>
                            </Select>
                        </FormControl>
                    </Grid>
                    <Grid size={{xs: 12, sm: 6}}>
                        <FormControl fullWidth>
                            <InputLabel>Error correction</InputLabel>
                            <Select value={errorCorrectionLevel} label="Error correction" onChange={(event: SelectChangeEvent) => setErrorCorrectionLevel(event.target.value as ErrorCorrectionLevel)}>
                                <MenuItem value="L">L (~7%)</MenuItem>
                                <MenuItem value="M">M (~15%)</MenuItem>
                                <MenuItem value="Q">Q (~25%)</MenuItem>
                                <MenuItem value="H">H (~30%)</MenuItem>
                            </Select>
                        </FormControl>
                    </Grid>
                    <Grid size={{xs: 12, sm: 6}}>
                        <TextField label="Foreground" type="color" value={dark} onChange={event => setDark(event.target.value)} fullWidth/>
                    </Grid>
                    <Grid size={{xs: 12, sm: 6}}>
                        <TextField label="Background" type="color" value={light} onChange={event => setLight(event.target.value)} fullWidth/>
                    </Grid>
                </Grid>
                <Box>
                    <Typography gutterBottom>Margin: {margin}</Typography>
                    <Slider value={margin} min={0} max={10} step={1} onChange={(_, value) => setMargin(value as number)}/>
                </Box>
                <Box>
                    <Typography gutterBottom>Scale: {scale}</Typography>
                    <Slider value={scale} min={2} max={16} step={1} onChange={(_, value) => setScale(value as number)}/>
                </Box>
                {(format === "image/jpeg" || format === "image/webp") && (
                    <Box>
                        <Typography gutterBottom>Quality: {quality}</Typography>
                        <Slider value={quality} min={0.1} max={1} step={0.05} onChange={(_, value) => setQuality(value as number)}/>
                    </Box>
                )}
                {dataUrl && (
                    <Box sx={{textAlign: "center"}}>
                        <Box component="img" src={dataUrl} alt="QR code" sx={{width: "100%", maxWidth: 360, borderRadius: 2}}/>
                    </Box>
                )}
                <Button
                    startIcon={<DownloadIcon/>}
                    href={dataUrl || undefined}
                    download={`qr-code.${extension}`}
                    disabled={!dataUrl}
                >
                    Download {extension.toUpperCase()}
                </Button>
            </Stack>
        </ToolSurface>
    );
};

export default QrTool;
